{
    ALLUSERSPROFILE: 'C:\\ProgramData',
        APPDATA: 'C:\\Users\\User\\AppData\\Roaming',
    COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-ERTOQQN',
    COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
    ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
    ChocolateyLastPathUpdate: '133091708649607704',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    EXEPATH: 'C:\\Program Files\\Git\\bin',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    HOME: 'C:\\Users\\User',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\User',
    IDEA_INITIAL_DIRECTORY: 'C:\\Windows\\system32',
    'IntelliJ IDEA': 'C:\\Program Files\\JetBrains\\IntelliJ IDEA 2022.2.2\\bin;',
    LOCALAPPDATA: 'C:\\Users\\User\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-ERTOQQN',
    MSYSTEM: 'MINGW64',
    NUMBER_OF_PROCESSORS: '12',
    OS: 'Windows_NT',
    OneDrive: 'C:\\Users\\User\\OneDrive',
    PATH: 'C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\User\\bin;C:\\Python311\\Scripts;C:\\Python311;C:\\Python310\\Scripts;C:\
\Python310;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\jav
    apath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\php;C:\\Progr
    amData\\chocolatey\\bin;C:\\Program Files\\nodejs;C:\\Program Files\\Git\\cmd;C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\
\PhpStorm 2022.2.1\\bin;C:\\php;C:\\Program Files\\JetBrains\\WebStorm 2022.3.1\\bin;C:\\Program Files\\JetBrains\\IntelliJ IDEA 2022.2.2\\bin;C:\\Users\\User\\App
    Data\\Roaming\\npm;C:\\Users\\User\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\User\\Desktop\\web\\backEnd\\test\\node_modules\\.bin',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
        PLINK_PROTOCOL: 'ssh',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 165 Stepping 3, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: 'a503',
    PROGRAMFILES: 'C:\\Program Files',
    PS1: '\\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
    PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    PWD: 'C:/Users/User/Desktop/web/backEnd/test',
    PhpStorm: 'C:\\Program Files\\JetBrains\\PhpStorm 2022.2.1\\bin;',
    ProgramData: 'C:\\ProgramData',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    SESSIONNAME: 'Console',
    SHLVL: '1',
    SYSTEMDRIVE: 'C:',
    SYSTEMROOT: 'C:\\Windows',
    TEMP: 'C:\\Users\\User\\AppData\\Local\\Temp',
    TERM: 'xterm-256color',
    TERMINAL_EMULATOR: 'JetBrains-JediTerm',
    TERM_SESSION_ID: 'b800bc64-2912-47f6-a490-6a94e7bc90cf',
    TMP: 'C:\\Users\\User\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-ERTOQQN',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-ERTOQQN',
    USERNAME: 'User',
    USERPROFILE: 'C:\\Users\\User',
    WINDIR: 'C:\\Windows',
    WebStorm: 'C:\\Program Files\\JetBrains\\WebStorm 2022.3.1\\bin;',
    ZES_ENABLE_SYSMAN: '1',
    _: 'C:/Program Files/nodejs/node',
    __INTELLIJ_COMMAND_HISTFILE__: 'C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2022.3\\terminal\\history\\test-history1'
}
